### ISSUE TITLE
ElevenLabs: Unknown Error Occurred

### ISSUE THREAD

**Issue by joshuadanpeterson** [veritas1/eleven-labs-obsidian-plugin#1]
<img width="347" alt="Screenshot 2023-10-26 at 02 48 57" src="https://github.com/veritas1/eleven-labs-obsidian-plugin/assets/6033094/dc9eb0de-a978-4a71-bac5-a556ccc602b6">

I recently downloaded the plugin, set up the API key, and attempted to generate an audio file when I got this error. I tried switching the voices and got the same result. Above is the error that showed when I ran the plugin. Below is the error that showed in the console.

```
Error: Request failed, status 400
  at new t (app.js:1:1827905)
  at z_ (app.js:1:1828097)
  at app.js:1:1828774
  at app.js:1:237027
  at Object.next (app.js:1:237132)
  at a (app.js:1:235850)
```

**Comment by veritas1** [comment]
Hi @joshuadanpeterson - Looks like a 400 HTTP response when calling the `/text-to-speech/<voice_id>` endpoint. I will make changes to make the cause of the issue more transparent. In the meantime, if you have the developer tools open, can you grab the request/response payloads from the 'network' tab, and share here?

**Comment by joshuadanpeterson** [comment]
Unfortunately I can't reproduce the bug. I ended up deleting the plugin and redownloading it, and now it works fine.

Thank you for building this plugin. I'm excited to see how it can enhance my Obsidian notes.
